version: '3.8'
services:
  app:
    build: .
    container_name: go-api-base
    volumes:
      - .:/app # Mount local directory for live updates
    ports:
      - '8080:8080'
    working_dir: /app
    command: ['air', '-c', 'air.toml']
